[package]
name = "clappy-clap-learning"
version = "0.1.0"
edition = "2021"
description = "The Tony Mushah's clappy-clap-learning cli."

[dependencies]
clap = { version = "4.5.21", features = ["derive", "unstable-doc"] }
